# Generated by Django 4.2.4 on 2023-08-12 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asistente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoría',
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_en',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
